name: Create docker image -- automated
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
        
      - name: install dependencies
        run: pip3 install requests beautifulsoup4
        
      - name: build ...
        run: ./build.sh
