name: Docker

on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          export $(echo '${{ github.event.head_commit.message }}' | sed 's/#.*//g' | xargs)
          docker build --build-arg RELEASE=$RELEASE \
            --build-arg MAJOR=$MAJOR \
            --build-arg MINOR=$MINOR \
            --build-arg PATCH=$PATCH \
            --tag sptkl/docker-geosupport:$MAJOR.$MINOR.$PATCH .

      - name: Log into registry
        run: docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets. DOCKER_PASSWORD }} 

      - name: Push image
        run: |
          docker push sptkl/docker-geosupport:$MAJOR.$MINOR.$PATCH
          docker tag sptkl/docker-geosupport:$MAJOR.$MINOR.$PATCH sptkl/docker-geosupport:latest
          docker push sptkl/docker-geosupport:latest