name: Create docker image -- Commit

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[build]')
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
    steps:
      - uses: actions/checkout@v2
        
      - name: install dependencies
        run: pip3 install requests beautifulsoup4
        
      - name: build ...
        run: ./build.sh